---
driver:
  name: dokken
  chef_version: 12.20.3
  privileged: true
transport:
  name: dokken
provisioner:
  name: dokken
verifier:
  name: inspec
platforms:
  - name: centos-7
    named_run_list: centos
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts sudo
    attributes:
      poise-service:
        redis:
          provider: systemd
  - name: centos-6
    named_run_list: centos
    driver:
      image: centos:6
      platform: rhel
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install which initscripts sudo
  - name: ubuntu-16.04
    named_run_list: debian
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -y
        - RUN /usr/bin/apt-get install sudo -y
    attributes:
      poise-service:
        redis:
          provider: systemd
  - name: ubuntu-14.04
    named_run_list: debian
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -y
        - RUN /usr/bin/apt-get install sudo -y
  - name: ubuntu-12.04
    named_run_list: debian
    driver:
      image: ubuntu:12.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -y
        - RUN /usr/bin/apt-get install sudo -y
  - name: debian-8
    named_run_list: debian
    driver:
      image: debian:8
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install lsb-release sudo -y
    attributes:
      poise-service:
        redis:
          provider: systemd
  - name: debian-7
    named_run_list: debian
    driver:
      image: debian:7
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install lsb-release sudo -y
suites:
  - name: default
    provisioner:
      policyfile: test/fixtures/policies/default.rb
  - name: sentinel
    provisioner:
      policyfile: test/fixtures/policies/sentinel.rb
  - name: archive
    provisioner:
      policyfile: test/fixtures/policies/default.rb
    attributes:
      blp-redis:
        provider: archive
        options:
          version: 3.2.3
